server:
  port: 8083

spring:
  application:
    name: availability-dgs
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:availabilitydb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  graphql:
    graphiql:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
